#Plugin configuration


extensionname="Too Many Files Pro"
site="fasterjoomla"

extension="toomanyfilespro"
folder_name="tooManyFiles/com_toomanyfiles_pro"

jdir=$SERVERSDIR/$site/public_html
sourcedir=$jdir/plugins/$plugin_type/$plugin_name
destdir=$JOOMLADEVDIR/$folder_name


webpage="http://www.fasterjoomla.com/extensions/too-many-files-optimize-js-and-css"
download="http://www.fasterjoomla.com/download/too-many-files"
jed="http://extensions.joomla.org/extensions/core-enhancements/performance/site-performance/26612"


VERSION=2.0.5
VERSION=2.0.5
VERSION=2.0.5
VERSION=2.0.5
